# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prlić Consulting d.o.o
email: ivan@prlic.io
description: >- # this means to ignore newlines until "baseurl:"
  DevOps Consulting & Cloud Architecture
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prlic.io" # the base hostname & protocol for your site, e.g. http://example.com
#linkedin_username: iprlic
#twitter_username: ivan_prlic
#github_username:  iprlic
author: Copyright &copy; 2021 - Prlić Consulting d.o.o.
recaptcha_key: 6LdR7T0dAAAAAETUVUtZu4vx1j8Vg3GSpN-kBc_c
form_post_url: https://europe-central2-prc-web-354213.cloudfunctions.net/send-email

social:
  name: Ivan Prlić
  links:
    - https://twitter.com/ivan_prlic
    - https://www.linkedin.com/in/iprlic
    - https://github.com/iprlic

# Build settings
markdown: kramdown
theme: minima
remote_theme: iprlic/creative-theme-jekyll-new
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
